name: Build Gomoku Calculator
permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create engine directory
        run: mkdir -p public/build

      - name: Download Rapfi data
        run: |
          curl -L \
            --fail \
            --retry 3 \
            -o public/build/rapfi.data \
            https://github.com/imnwngr/rapfi/releases/download/v1.0-neutral/rapfi.data

      - name: Check Rapfi files
        run: |
          ls -lh public/build

          test -f public/build/rapfi-single-simd128.js
          test -f public/build/rapfi-single-simd128.wasm
          test -f public/build/rapfi.data

      - name: Build frontend
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build

      - name: Check production engine
        run: |
          ls -lh dist/build

          test -f dist/build/rapfi-single-simd128.js
          test -f dist/build/rapfi-single-simd128.wasm
          test -f dist/build/rapfi.data

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
